# Loading and Consolidation of CO2 Emission Datasets

This notebook loads several CSV files containing CO2 emission data from vehicles across different periods and consolidates them into a single database.

## 1. Imports and Configurations

We import the pandas library and the path constants defined in the project configuration file.

In [21]:
import pandas as pd

from src.config import (
    DATA_2005_2014,
    DATA_2015_2019,
    DATA_2020,
    DATA_2021,
    DATA_2022,
    DATA_2023,
    DATA_2024,
    CONSOLIDATED_DATA,
)

## 2. Loading Data

We read the individual CSV files. Note that for the years 2023 and 2024, it is necessary to specify 'latin' encoding.

In [22]:
df_2005_2014 = pd.read_csv(DATA_2005_2014)
df_2015_2019 = pd.read_csv(DATA_2015_2019)
df_2020 = pd.read_csv(DATA_2020)
df_2021 = pd.read_csv(DATA_2021)
df_2022 = pd.read_csv(DATA_2022)
df_2023 = pd.read_csv(DATA_2023, encoding="latin")
df_2024 = pd.read_csv(DATA_2024, encoding="latin")

## 3. Initial Inspection (Sanity Checks)

We check the first few rows of each loaded DataFrame to ensure the data was read correctly.

In [23]:
df_2005_2014.head()

,Model year,Make,Model,Vehicle class,Engine size (L),Cylinders,Transmission,Fuel type,City (L/100 km),Highway (L/100 km),Combined (L/100 km),Combined (mpg),CO2 emissions (g/km),CO2 rating,Smog rating
0,2005,Acura,1.7EL,Compact,1.7,4,A4,X,9.2,7.2,8.3,34,191,NaN,NaN
1,2005,Acura,1.7EL,Compact,1.7,4,M5,X,9.1,7.3,8.3,34,191,NaN,NaN
2,2005,Acura,MDX AWD,Sport utility vehicle,3.5,6,A5,Z,15.9,11.1,13.7,21,315,NaN,NaN
3,2005,Acura,NSX,Two-seater,3.0,6,AS4,Z,15.1,10.5,13.0,22,299,NaN,NaN
4,2005,Acura,NSX,Two-seater,3.2,6,M6,Z,15.1,10.5,13.0,22,299,NaN,NaN

In [24]:
df_2015_2019.head()

,Model year,Make,Model,Vehicle class,Engine size (L),Cylinders,Transmission,Fuel type,City (L/100 km),Highway (L/100 km),Combined (L/100 km),Combined (mpg),CO2 emissions (g/km),CO2 rating,Smog rating
0,2015,Acura,ILX,Compact,2.0,4,AS5,Z,9.7,6.7,8.3,34,191,NaN,NaN
1,2015,Acura,ILX,Compact,2.4,4,M6,Z,10.8,7.4,9.3,30,214,NaN,NaN
2,2015,Acura,ILX Hybrid,Compact,1.5,4,AV7,Z,6.0,6.1,6.1,46,140,NaN,NaN
3,2015,Acura,MDX SH-AWD,Sport utility vehicle: Small,3.5,6,AS6,Z,12.7,9.1,11.1,25,255,NaN,NaN
4,2015,Acura,RDX AWD,Sport utility vehicle: Small,3.5,6,AS6,Z,12.1,8.7,10.6,27,244,NaN,NaN

In [25]:
df_2020.head()

,Model year,Make,Model,Vehicle class,Engine size (L),Cylinders,Transmission,Fuel type,City (L/100 km),Highway (L/100 km),Combined (L/100 km),Combined (mpg),CO2 emissions (g/km),CO2 rating,Smog rating
0,2020,Acura,ILX,Compact,2.4,4,AM8,Z,9.9,7.0,8.6,33,199,6,3
1,2020,Acura,MDX SH-AWD,Sport utility vehicle: Small,3.5,6,AS9,Z,12.3,9.2,10.9,26,254,4,3
2,2020,Acura,MDX SH-AWD A-SPEC,Sport utility vehicle: Small,3.5,6,AS9,Z,12.2,9.5,11.0,26,258,4,3
3,2020,Acura,MDX Hybrid AWD,Sport utility vehicle: Small,3.0,6,AM7,Z,9.1,9.0,9.0,31,210,5,3
4,2020,Acura,NSX,Two-seater,3.5,6,AM9,Z,11.1,10.8,11.0,26,261,4,3

In [26]:
df_2021.head()

,Model year,Make,Model,Vehicle class,Engine size (L),Cylinders,Transmission,Fuel type,City (L/100 km),Highway (L/100 km),Combined (L/100 km),Combined (mpg),CO2 emissions (g/km),CO2 rating,Smog rating
0,2021,Acura,ILX,Compact,2.4,4,AM8,Z,9.9,7.0,8.6,33,199,6,3
1,2021,Acura,NSX,Two-seater,3.5,6,AM9,Z,11.1,10.8,11.0,26,256,4,3
2,2021,Acura,RDX SH-AWD,Sport utility vehicle: Small,2.0,4,AS10,Z,11.0,8.6,9.9,29,232,5,6
3,2021,Acura,RDX SH-AWD A-SPEC,Sport utility vehicle: Small,2.0,4,AS10,Z,11.3,9.1,10.3,27,242,5,6
4,2021,Acura,TLX SH-AWD,Compact,2.0,4,AS10,Z,11.2,8.0,9.8,29,230,5,7

In [27]:
df_2022.head()

,Model year,Make,Model,Vehicle class,Engine size (L),Cylinders,Transmission,Fuel type,City (L/100 km),Highway (L/100 km),Combined (L/100 km),Combined (mpg),CO2 emissions (g/km),CO2 rating,Smog rating
0,2022,Acura,ILX,Compact,2.4,4,AM8,Z,9.9,7.0,8.6,33,200,6,3
1,2022,Acura,MDX SH-AWD,Sport utility vehicle: Small,3.5,6,AS10,Z,12.6,9.4,11.2,25,263,4,5
2,2022,Acura,MDX Type S,Sport utility vehicle: Standard,3.0,6,AS10,Z,13.8,11.2,12.4,23,291,4,5
3,2022,Acura,NSX,Two-seater,3.5,6,AM9,Z,11.1,10.8,11.0,26,256,5,3
4,2022,Acura,RDX SH-AWD,Sport utility vehicle: Small,2.0,4,AS10,Z,11.0,8.6,9.9,29,232,5,6

In [28]:
df_2023.head()

,Model year,Make,Model,Vehicle class,Engine size (L),Cylinders,Transmission,Fuel type,City (L/100 km),Highway (L/100 km),Combined (L/100 km),Combined (mpg),CO2 emissions (g/km),CO2 rating,Smog rating
0,2023,Acura,Integra,Full-size,1.5,4,AV7,Z,7.9,6.3,7.2,39,167,6,7
1,2023,Acura,Integra A-SPEC,Full-size,1.5,4,AV7,Z,8.1,6.5,7.4,38,172,6,7
2,2023,Acura,Integra A-SPEC,Full-size,1.5,4,M6,Z,8.9,6.5,7.8,36,181,6,6
3,2023,Acura,MDX SH-AWD,Sport utility vehicle: Small,3.5,6,AS10,Z,12.6,9.4,11.2,25,263,4,5
4,2023,Acura,MDX SH-AWD Type S,Sport utility vehicle: Standard,3.0,6,AS10,Z,13.8,11.2,12.4,23,291,4,5

In [29]:
df_2024.head()

,Model year,Make,Model,Vehicle class,Engine size (L),Cylinders,Transmission,Fuel type,City (L/100 km),Highway (L/100 km),Combined (L/100 km),Combined (mpg),CO2 emissions (g/km),CO2 rating,Smog rating
0,2024,Acura,Integra A-SPEC,Full-size,1.5,4,AV7,Z,8.1,6.5,7.4,38,172,6,7
1,2024,Acura,Integra A-SPEC,Full-size,1.5,4,M6,Z,8.9,6.5,7.8,36,181,6,6
2,2024,Acura,Integra Type S,Full-size,2.0,4,M6,Z,11.1,8.3,9.9,29,230,5,6
3,2024,Acura,MDX SH-AWD,Sport utility vehicle: Small,3.5,6,AS10,Z,12.6,9.4,11.2,25,263,4,5
4,2024,Acura,MDX SH-AWD Type S,Sport utility vehicle: Standard,3.0,6,AS10,Z,13.8,11.2,12.4,23,291,4,5

## 4. Consolidação das Bases

Concatenamos todos os DataFrames em um único objeto e resetamos o índice para manter a continuidade.

In [30]:
# Consolidando bases e resetando índice
df = pd.concat(
    [df_2005_2014, df_2015_2019, df_2020, df_2021, df_2022, df_2023, df_2024]
)

df = df.reset_index(drop=True)

df.head()

,Model year,Make,Model,Vehicle class,Engine size (L),Cylinders,Transmission,Fuel type,City (L/100 km),Highway (L/100 km),Combined (L/100 km),Combined (mpg),CO2 emissions (g/km),CO2 rating,Smog rating
0,2005,Acura,1.7EL,Compact,1.7,4,A4,X,9.2,7.2,8.3,34,191,NaN,NaN
1,2005,Acura,1.7EL,Compact,1.7,4,M5,X,9.1,7.3,8.3,34,191,NaN,NaN
2,2005,Acura,MDX AWD,Sport utility vehicle,3.5,6,A5,Z,15.9,11.1,13.7,21,315,NaN,NaN
3,2005,Acura,NSX,Two-seater,3.0,6,AS4,Z,15.1,10.5,13.0,22,299,NaN,NaN
4,2005,Acura,NSX,Two-seater,3.2,6,M6,Z,15.1,10.5,13.0,22,299,NaN,NaN

## 5. Perfilamento dos Dados Consolidados

Analisamos a estrutura final da base consolidada, verificando o final da tabela e informações gerais das colunas.

In [31]:
df.tail()

,Model year,Make,Model,Vehicle class,Engine size (L),Cylinders,Transmission,Fuel type,City (L/100 km),Highway (L/100 km),Combined (L/100 km),Combined (mpg),CO2 emissions (g/km),CO2 rating,Smog rating
20516,2024,Volvo,V60 CC B5 AWD,Station wagon: Small,2.0,4,AS8,Z,10.0,7.5,8.9,32,207,5.0,5.0
20517,2024,Volvo,V90 CC B6 AWD,Station wagon: Mid-size,2.0,4,AS8,Z,10.7,8.1,9.5,30,223,5.0,7.0
20518,2024,Volvo,XC40 B5 AWD,Sport utility vehicle: Small,2.0,4,AS8,Z,9.9,7.8,9.0,31,210,5.0,5.0
20519,2024,Volvo,XC60 B5 AWD,Sport utility vehicle: Small,2.0,4,AS8,Z,10.6,8.3,9.6,29,226,5.0,5.0
20520,2024,Volvo,XC90 B6 AWD,Sport utility vehicle: Standard,2.0,4,AS8,Z,10.9,8.6,9.8,29,230,5.0,7.0

In [32]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 20521 entries, 0 to 20520
Data columns (total 15 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   Model year            20521 non-null  int64
 1   Make                  20521 non-null  str
 2   Model                 20521 non-null  str
 3   Vehicle class         20521 non-null  str
 4   Engine size (L)       20521 non-null  float64
 5   Cylinders             20521 non-null  int64
 6   Transmission          20521 non-null  str
 7   Fuel type             20521 non-null  str
 8   City (L/100 km)       20521 non-null  float64
 9   Highway (L/100 km)    20521 non-null  float64
 10  Combined (L/100 km)   20521 non-null  float64
 11  Combined (mpg)        20521 non-null  int64
 12  CO2 emissions (g/km)  20521 non-null  int64
 13  CO2 rating            8832 non-null   float64
 14  Smog rating           7726 non-null   float64
dtypes: float64(6), int64(4), str(5)
memory usage: 2.3 MB

## 6. Exemplos de Consultas (Queries)

Realizamos algumas filtragens para demonstrar como buscar informações específicas na base, como veículos da marca Audi.

In [33]:
df.query("Make == 'Audi'")

,Model year,Make,Model,Vehicle class,Engine size (L),Cylinders,Transmission,Fuel type,City (L/100 km),Highway (L/100 km),Combined (L/100 km),Combined (mpg),CO2 emissions (g/km),CO2 rating,Smog rating
13,2005,Audi,A4,Compact,1.8,4,AV,Z,11.8,8.7,10.4,27,239,NaN,NaN
14,2005,Audi,A4 quattro,Compact,1.8,4,AS5,Z,13.2,9.0,11.3,25,260,NaN,NaN
15,2005,Audi,A4 quattro,Compact,1.8,4,M6,Z,12.7,8.6,10.8,26,248,NaN,NaN
16,2005,Audi,A4 quattro,Compact,3.0,6,AS5,Z,14.5,9.9,12.4,23,285,NaN,NaN
17,2005,Audi,A4 quattro,Compact,3.0,6,M6,Z,14.5,9.8,12.4,23,285,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
19803,2024,Audi,S8 quattro,Full-size,4.0,8,AS8,Z,16.0,10.0,13.3,21,312,4.0,3.0
19804,2024,Audi,SQ5 quattro,Sport utility vehicle: Small,3.0,6,AS8,Z,12.6,9.8,11.4,25,266,4.0,5.0
19805,2024,Audi,SQ5 Sportback quattro,Sport utility vehicle: Small,3.0,6,AS8,Z,12.6,9.8,11.4,25,266,4.0,5.0
19806,2024,Audi,SQ7 quattro,Sport utility vehicle: Standard,4.0,8,AS8,Z,16.0,11.5,13.9,20,326,3.0,3.0
19807,2024,Audi,SQ8 quattro,Sport utility vehicle: Standard,4.0,8,AS8,Z,15.6,11.5,13.8,20,322,3.0,3.0

In [34]:
df.query("Make == 'Audi' and Model.str.contains('Coup')")

,Model year,Make,Model,Vehicle class,Engine size (L),Cylinders,Transmission,Fuel type,City (L/100 km),Highway (L/100 km),Combined (L/100 km),Combined (mpg),CO2 emissions (g/km),CO2 rating,Smog rating
42,2005,Audi,TT Coupe,Minicompact,1.8,4,AS6,Z,12.8,8.9,11.0,26,253,NaN,NaN
43,2005,Audi,TT Coupe quattro,Minicompact,1.8,4,M6,Z,13.2,9.0,11.3,25,260,NaN,NaN
44,2005,Audi,TT Coupe quattro,Minicompact,3.2,6,AS6,Z,12.0,9.6,10.9,26,251,NaN,NaN
1053,2006,Audi,TT Coupe quattro,Minicompact,1.8,4,M6,Z,13.2,9.0,11.3,25,260,NaN,NaN
1054,2006,Audi,TT Coupe quattro,Minicompact,3.2,6,AS6,Z,13.8,9.8,12.0,24,276,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
18978,2023,Audi,TT Coupé 45 TFSI quattro,Subcompact,2.0,4,AM7,X,10.5,8.0,9.4,30,221,5.0,7.0
18980,2023,Audi,TTS Coupé quattro,Subcompact,2.0,4,AM7,Z,10.0,7.7,9.0,31,209,5.0,3.0
19776,2024,Audi,A5 Coupé 45 TFSI quattro,Subcompact,2.0,4,AM7,Z,10.0,7.4,8.8,32,208,5.0,5.0
19791,2024,Audi,RS 5 Coupé,Subcompact,2.9,6,AS8,Z,12.9,9.3,11.3,25,264,4.0,5.0
19799,2024,Audi,S5 Coupé quattro,Subcompact,3.0,6,AS8,Z,11.1,8.1,9.7,29,228,5.0,5.0

In [35]:
df["Model year"]

0        2005
1        2005
2        2005
3        2005
4        2005
         ...
20516    2024
20517    2024
20518    2024
20519    2024
20520    2024
Name: Model year, Length: 20521, dtype: int64

https://www.youtube.com/watch?v=sQWpUE1HH2Q

## 7. Padronização dos Nomes das Colunas

Aplicamos uma padronização snake_case aos nomes das colunas para facilitar o uso no desenvolvimento e análise.

In [36]:
import re


def string_to_snake_case(string):
    string = re.sub("/", " ", string)                       # substitui / por espaço
    string = re.sub(" +", " ", string)                      # substitui múltiplos espaços por um espaço
    string = re.sub(" ", "_", string)                       # substitui espaço por _
    string = re.sub("([a-z0-9])([A-Z])", r"\1_\2", string)  # adiciona _ entre letras minúsculas e maiúsculas
    string = re.sub(r"\(", "", string)                      # elimina parênteses
    string = re.sub(r"\)", "", string)                      # elimina parênteses
    return string.lower()                                   # retorna a string em minúsculo

In [37]:
[string_to_snake_case(coluna) for coluna in df.columns]

['model_year',
 'make',
 'model',
 'vehicle_class',
 'engine_size_l',
 'cylinders',
 'transmission',
 'fuel_type',
 'city_l_100_km',
 'highway_l_100_km',
 'combined_l_100_km',
 'combined_mpg',
 'co2_emissions_g_km',
 'co2_rating',
 'smog_rating']

In [38]:
df.columns = [string_to_snake_case(coluna) for coluna in df.columns]

df.head()

,model_year,make,model,vehicle_class,engine_size_l,cylinders,transmission,fuel_type,city_l_100_km,highway_l_100_km,combined_l_100_km,combined_mpg,co2_emissions_g_km,co2_rating,smog_rating
0,2005,Acura,1.7EL,Compact,1.7,4,A4,X,9.2,7.2,8.3,34,191,NaN,NaN
1,2005,Acura,1.7EL,Compact,1.7,4,M5,X,9.1,7.3,8.3,34,191,NaN,NaN
2,2005,Acura,MDX AWD,Sport utility vehicle,3.5,6,A5,Z,15.9,11.1,13.7,21,315,NaN,NaN
3,2005,Acura,NSX,Two-seater,3.0,6,AS4,Z,15.1,10.5,13.0,22,299,NaN,NaN
4,2005,Acura,NSX,Two-seater,3.2,6,M6,Z,15.1,10.5,13.0,22,299,NaN,NaN

In [39]:
df["model_year"]

0        2005
1        2005
2        2005
3        2005
4        2005
         ...
20516    2024
20517    2024
20518    2024
20519    2024
20520    2024
Name: model_year, Length: 20521, dtype: int64

## 8. Salvamento da Base Consolidada

Exportamos o DataFrame final para o formato Parquet, que é mais eficiente em armazenamento e leitura.

In [40]:
df.to_parquet(CONSOLIDATED_DATA, index=False)